version: '1'

services:
  database:
    container_name: todo
    image: postgres
    restart: always
    env_file: .env
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - db-data:/var/lib/postgresql/data/
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 10s
      timeout: 30s
      retries: 30
      start_period: 80s
  db_admin:
    container_name: todo_pgAmin
    image: dpage/pgadmin4
    env_file: .env
    ports:
      - '80'
    volumes:
      - pg-amdmin:/var/lib/pgadmin
volumes:
  db-data:
  pg-amdmin:
